class Endpoints:
    """"""
    BASE = "https://api.truckersmp.com/v2"
    PLAYER_LOOKUP = f"{BASE}/player/"
    BANS_LOOKUP = f"{BASE}/bans/"
    SERVERS = f"{BASE}/servers"
    INGAME_TIME = f"{BASE}/game_time"
    EVENTS = f"{BASE}/events"
    EVENT_LOOKUP = f"{BASE}/events/"
    VTCS = f"{BASE}/vtc"
    VTC_LOOKUP = f"{BASE}/vtc/"
    VTC_NEWS = "/news/"
    VTC_ROLES = "/roles/"
    VTC_MEMBERS = "/members/"
    VTC_EVENTS = "/events/"
    VERSION = f"{BASE}/version/"
    RULES = f"{BASE}/rules/"
